#!/usr/bin/env node
// Build script to inject environment variables into static files

const fs = require('fs');
const path = require('path');

// Get environment variables
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

console.log('🔨 Build: Injecting environment variables...');
console.log(`URL: ${SUPABASE_URL ? 'Found' : 'Missing'}`);
console.log(`Key: ${SUPABASE_ANON_KEY ? 'Found' : 'Missing'}`);

// Create env-config.js with actual values
const envConfig = `// Auto-generated by build process - DO NOT EDIT
window.SUPABASE_URL = '${SUPABASE_URL}';
window.SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';

// Log injection status
console.log('✅ Environment variables injected:', {
    url: window.SUPABASE_URL ? 'Set' : 'Missing',
    key: window.SUPABASE_ANON_KEY ? 'Set' : 'Missing',
    timestamp: new Date().toISOString()
});
`;

// Write the config file
fs.writeFileSync(path.join(__dirname, 'env-config.js'), envConfig);

console.log('✅ Build complete: env-config.js created');