version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./backups:/backups
    networks:
      - property-network

  # Optional: Backup Service
  backup:
    image: alpine:latest
    volumes:
      - ./backups:/backups
      - property-data:/data
    environment:
      - BACKUP_INTERVAL=86400  # 24 hours
    command: |
      sh -c "while true; do
        echo 'Creating backup...'
        tar -czf /backups/backup-$$(date +%Y%m%d-%H%M%S).tar.gz /data
        find /backups -name 'backup-*.tar.gz' -mtime +30 -delete
        sleep $$BACKUP_INTERVAL
      done"
    networks:
      - property-network

volumes:
  property-data:

networks:
  property-network:
    driver: bridge